theme: jekyll-theme-cayman
title: The IdolFest Foundation
email: contact@idolfest.org
description: The IdolFest Foundation is bringing Japanese idol culture to North America. Join us at our events, or get involved with our online programming.
permalink: pretty
